seglo/kafka-lag-exporter

README.md

Just removing a duplicated word/subtitle.

Remove duplicated subtitle in the README

---

charts/kafka-lag-exporter/templates/030-Deployment.yaml
charts/kafka-lag-exporter/values.yaml
src/main/scala/com/lightbend/kafkalagexporter/AppConfig.scala
src/main/scala/com/lightbend/kafkalagexporter/ConsumerGroupCollector.scala
src/main/scala/com/lightbend/kafkalagexporter/KafkaClient.scala
src/main/scala/com/lightbend/kafkalagexporter/KafkaClusterManager.scala
src/main/scala/com/lightbend/kafkalagexporter/MainApp.scala
src/test/scala/com/lightbend/kafkalagexporter/ConsumerGroupCollectorSpec.scala

This PR add configuration options for security protocol, SASL mechanism and JAAS configuration for the clusters.

Support TLS/SASL enabled clusters

---

grafana/Kafka_Lag_Exporter_Dashboard.json

kafka_consumergroup_group_lag_seconds related graph is already defined at line 190. This is repeated again at line 364. It should be kafka_consumergroup_group_lag

fix repeated graph in grafana (add missing graph)

---

README.md
charts/kafka-lag-exporter/templates/030-ConfigMap.yaml
charts/kafka-lag-exporter/values.yaml
src/main/scala/com/lightbend/kafkalagexporter/AppConfig.scala
src/main/scala/com/lightbend/kafkalagexporter/ConsumerGroupCollector.scala
src/main/scala/com/lightbend/kafkalagexporter/KafkaClient.scala
src/test/scala/com/lightbend/kafkalagexporter/AppConfigSpec.scala

Support arbitrary kafka client configuration

---

src/main/scala/com/lightbend/kafkalagexporter/KafkaClient.scala
src/test/scala/com/lightbend/kafkalagexporter/KafkaClientSpec.scala

Get commit offset for correct group topic partitions

---

charts/kafka-lag-exporter/templates/040-Deployment.yaml

A very small update to the helm chart to support custom annotations in the values files. This is necessary to allow datadog to autodiscover prometheus metrics based on pod annotations.

Adding support for custom annotations on pods

---

README.md
charts/kafka-lag-exporter/templates/030-ConfigMap.yaml
charts/kafka-lag-exporter/values.yaml
examples/standalone/application.conf
src/main/resources/reference.conf
src/main/scala/com/lightbend/kafkalagexporter/AppConfig.scala
src/main/scala/com/lightbend/kafkalagexporter/MainApp.scala
src/main/scala/com/lightbend/kafkalagexporter/MetricsSink.scala
src/main/scala/com/lightbend/kafkalagexporter/PrometheusEndpointSink.scala
src/test/scala/com/lightbend/kafkalagexporter/AppConfigSpec.scala

This fixes [34](https://github.com/lightbend/kafka-lag-exporter/issues/34). This would help to specify custom / additional labels which could be specified per cluster.
```
Example:
kafka-lag-exporter {
port = 9999
lookup-table-size = 60
clusters = [
{
name = "us-east_ny_a-cluster"                                   
bootstrap-brokers = "us-east_ny_a-1.cluster-a.xyzcorp.com:9092,us-east_ny_a-2.cluster-a.xyzcorp.com:9092,us-east_ny_a-3.cluster-a.xyzcorp.com:9092"
labels {
location = "ny"
zone = "us-east"
}
}
]
}
```
This would simplify the Prometheus job config. Because now Prometheus relabelling tricks must be applied to get this labels.

Adds custom labels for every cluster

---

README.md
charts/kafka-lag-exporter/templates/030-ConfigMap.yaml
charts/kafka-lag-exporter/values.yaml
src/main/resources/reference.conf
src/main/scala/com/lightbend/kafkalagexporter/AppConfig.scala
src/main/scala/com/lightbend/kafkalagexporter/MainApp.scala
src/main/scala/com/lightbend/kafkalagexporter/PrometheusEndpointSink.scala
src/test/scala/com/lightbend/kafkalagexporter/PrometheusEndpointSinkTest.scala

This PR addresses: #43
New configuration exposed: metric-whitelist. PrometheusEndpointSink will report or remove metrics based on the list of regex.
This PR also added test cases for PrometheusEndpointSink, and fix a bug where metrics removal does not consider global tags.

Adding support to control which prometheus metrics to expose

---

README.md
charts/kafka-lag-exporter/templates/030-ConfigMap.yaml
charts/kafka-lag-exporter/values.yaml
project/Dependencies.scala
src/main/resources/reference.conf
src/main/scala/com/lightbend/kafkalagexporter/AppConfig.scala
src/main/scala/com/lightbend/kafkalagexporter/KafkaClient.scala
src/test/scala/com/lightbend/kafkalagexporter/KafkaClientSpec.scala
src/test/scala/com/lightbend/kafkalagexporter/TestData.scala

I am running a snapshot Docker image of this right now, everything seems to work fine using the following `application.conf`
```
kafka-lag-exporter {
clusters = [
{
name = "dev"
bootstrap-brokers = "broker1:9092,broker2:9092,broker3:9092"
consumer-properties = {
client.id = "kafka-lag"
}
admin-client-properties = {
client.id = "kafka-lag-admin"
}
}
]
lookup-table-size = 200
client-group-id = "test-kafkalagexporter"
metric-whitelist = ["kafka_consumergroup_group_lag_seconds"]
topic-whitelist = ["prefix1-.*", "prefix2-.*"]
}
```

Allow whitelisting Kafka topics

---

README.md
charts/kafka-lag-exporter/templates/000-ServiceAccount.yaml
charts/kafka-lag-exporter/templates/040-Deployment.yaml
charts/kafka-lag-exporter/values.yaml

Addresses https://github.com/lightbend/kafka-lag-exporter/issues/53.
In this PR, i generate the service account dynamically, rather than using a user input as originally discussed in issue 53. If we rely on user input, the helm chart will fail if it is executed twice under different helm release name, as the service account would have already existed.

Omit service account generation when not using strimzi (#53)

---

README.md
charts/kafka-lag-exporter/templates/030-ConfigMap.yaml
charts/kafka-lag-exporter/values.yaml
src/main/resources/reference.conf
src/main/scala/com/lightbend/kafkalagexporter/AppConfig.scala
src/main/scala/com/lightbend/kafkalagexporter/KafkaClient.scala
src/test/scala/com/lightbend/kafkalagexporter/AppConfigSpec.scala
src/test/scala/com/lightbend/kafkalagexporter/KafkaClientSpec.scala

Implement consumer group whitelist & misc. refactorings

---

charts/kafka-lag-exporter/templates/040-Deployment.yaml

Extra whitespace is being removed while templating `serviceAccountName` in file `charts/kafka-lag-exporter/templates/040-Deployment.yaml`
This leads to the following error when templating/installing the helm chart with `watchers.strimzi` or `serviceAccount.create` enabled:
```
Error: UPGRADE FAILED: YAML parse error on kafka-lag-exporter/templates/040-Deployment.yaml: error converting YAML to JSON: yaml: line 21: mapping values are not allowed in this context
```
This happens because it is being templated as:
```
spec: serviceAccountName: {{ include "kafka-lag-exporter.fullname" . }}-serviceaccount
```
instead of 
```
spec: 
serviceAccountName: {{ include "kafka-lag-exporter.fullname" . }}-serviceaccount
```

Fix Helm Chart: Whitespace in Deployment.yaml

---

README.md
charts/kafka-lag-exporter/values.yaml
src/main/scala/com/lightbend/kafkalagexporter/PrometheusEndpointSink.scala
src/test/scala/com/lightbend/kafkalagexporter/PrometheusEndpointSinkTest.scala

Due to issues with registering duplicate metrics I had to roll back cluster labels support (#61) until a new solution that supports multiple custom cluster labels is supported.
The problem is recreated in PR #78.

Revert cluster labels

---

README.md
charts/kafka-lag-exporter/values.yaml
src/main/scala/com/lightbend/kafkalagexporter/AppConfig.scala
src/main/scala/com/lightbend/kafkalagexporter/PrometheusEndpointSink.scala
src/test/scala/com/lightbend/kafkalagexporter/AppConfigSpec.scala
src/test/scala/com/lightbend/kafkalagexporter/PrometheusEndpointSinkTest.scala

This fixes the issue reproduced in [78](https://github.com/lightbend/kafka-lag-exporter/pull/78).
Java prometheus client library does not let us register metrics more than once with different sets of labels. The idea is not to register prometheus metrics for each cluster and to create once with all the labels defined in all the cluster.

Avoid recreating the metrics for each cluster to support global labels

---

README.md
scripts/update_readme_version.sh
src/main/scala/com/lightbend/kafkalagexporter/ConsumerGroupCollector.scala
src/main/scala/com/lightbend/kafkalagexporter/KafkaClient.scala
src/main/scala/com/lightbend/kafkalagexporter/Metrics.scala
src/test/scala/com/lightbend/kafkalagexporter/ConsumerGroupCollectorSpec.scala

kafka_partition_earliest_offset is now gathered and exported for all of the topic partitions which had been gathering the latest offset. Closes #67

Added collection and export of Earliest Offset

---

charts/kafka-lag-exporter/templates/060-ServiceMonitor.yaml
charts/kafka-lag-exporter/values.yaml

Update helm chart to template out Prometheus ServiceMonitor `interval` & `scrapeTimeout`.

[helm chart] Template Out ServiceMonitor interval & scrapeTimeout

---

charts/kafka-lag-exporter/templates/040-Deployment.yaml

`Deployment` is no longer part of `apps/v1beta` in later releases.

Upgrade Deployment apiversion to v1/apps

---

charts/kafka-lag-exporter/Chart.yaml
charts/kafka-lag-exporter/templates/060-ServiceMonitor.yaml
charts/kafka-lag-exporter/values.yaml

Make the ServiceMonitor Namespace & Labels configurable.
This MR makes configuring prometheus auto discovery easier for the
following things:
* Generally, the ServiceMonitors may be in a separate namespace (the one
in which prometheus is deployed).
* Prometheus only discovers ServiceMonitors that have certain labels on them.
Also bumped helm chart patch version.

Template Service Monitor Namespace & Labels

---

charts/kafka-lag-exporter/templates/040-Deployment.yaml
charts/kafka-lag-exporter/values.yaml

Moved annotations to pod template and fixed variable typo

Fixed pod annotations support in helm chart

---

charts/kafka-lag-exporter/templates/040-Deployment.yaml
charts/kafka-lag-exporter/values.yaml

Support mounting extra configmaps in pods. This can e.g. be used to provide a truststore if needed for TLS enabled clusters.

Allow mounting extra configmaps in pod

---

README.md
src/main/scala/com/lightbend/kafkalagexporter/ConsumerGroupCollector.scala
src/main/scala/com/lightbend/kafkalagexporter/Metrics.scala
src/test/scala/com/lightbend/kafkalagexporter/ConsumerGroupCollectorSpec.scala

In regards to #92, add a metric to represent a consumer group's total offset lag per topic.
---
New metric:
**`kafka_consumergroup_group_topic_lag`**
Labels: `cluster_name, group, topic`
_The sum of the difference between the last produced offset and the last consumed offset of all partitions in this topic for this group._
---
I'm on fence about the metric name itself. Some things that came to mind:
- `kafka_consumergroup_group_topic_lag` (current proposal)
- `kafka_consumergroup_group_total_lag` (original proposal)
- `kafka_consumergroup_topic_lag`

Add metric to represent a consumer group's total offset lag per topic

---

charts/kafka-lag-exporter/values.yaml

Fix _prometheus.serviceMonitor.interval_ type from integer to string in the default values.
Otherwise enabling ServiceMonitor in the helm chart results in an error like this:
```
Error: release kafka-lag-exporter failed: ServiceMonitor.monitoring.coreos.com "kafka-lag-exporter" is invalid: []: Invalid value: map[string]interface {}{"kind":"ServiceMonitor", "metadata":map[string]interface {}{"generation":1, "uid":"76063bad-0cf5-11ea-8416-0cc47a338560", "name":"kafka-lag-exporter", "namespace":"monitoring", "creationTimestamp":"2019-11-22T06:58:17Z", "labels":map[string]interface {}{"app":"kafka-lag-exporter", "app.kubernetes.io/instance":"kafka-lag-exporter", "app.kubernetes.io/managed-by":"Tiller", "app.kubernetes.io/name":"kafka-lag-exporter", …
```

Helm Chart: Fix ServiceMonitor Interval Type To String

---

README.md
build.sbt

Java App Packaging for non-Docker envs

---

README.md
examples/standalone/application.conf
src/main/resources/reference.conf
src/main/scala/com/lightbend/kafkalagexporter/AppConfig.scala
src/main/scala/com/lightbend/kafkalagexporter/ConsumerGroupCollector.scala
src/main/scala/com/lightbend/kafkalagexporter/EndpointSink.scala
src/main/scala/com/lightbend/kafkalagexporter/GraphiteConfig.scala
src/main/scala/com/lightbend/kafkalagexporter/GraphiteEndpointSink.scala
src/main/scala/com/lightbend/kafkalagexporter/KafkaClusterManager.scala
src/main/scala/com/lightbend/kafkalagexporter/MainApp.scala
src/main/scala/com/lightbend/kafkalagexporter/PrometheusConfig.scala
src/main/scala/com/lightbend/kafkalagexporter/PrometheusEndpointSink.scala
src/test/scala/com/lightbend/kafkalagexporter/ConsumerGroupCollectorSpec.scala
src/test/scala/com/lightbend/kafkalagexporter/GraphiteEndpointSinkTest.scala
src/test/scala/com/lightbend/kafkalagexporter/PrometheusEndpointSinkTest.scala

This allows to specify a graphite output via the following config:
```
graphite-host = "localhost"
graphite-port = 2003
```
This translates prometheus labels into a graphite metric path.

Add graphite support

---

src/main/scala/com/lightbend/kafkalagexporter/KafkaClient.scala

This is a fix for the issue https://github.com/lightbend/kafka-lag-exporter/issues/126 .
It allows to report lag for the consumer groups that don't have members information. 
Such situation is actually happening for the consumers running under Flink.
Also minor fix in setting properties, KafkaClient.scala lines 61 and 73:
the documentation for java.util.Properties suggests not to use putAll method because it is not type-safe (in fact, in my environment those two lines did not compile). They suggest using setProperty method.
I tested this fix in my local environment.

Support consumer groups for which member information is unavailable.

---

charts/kafka-lag-exporter/templates/000-ServiceAccount.yaml
charts/kafka-lag-exporter/templates/040-Deployment.yaml
charts/kafka-lag-exporter/values.yaml

This PR add support for configuring init containers for the pod. The usecase for these can be many, but e.g. for adding secrets from an external source. In addition to support for adding the init container specs, the PR adds support for:
- Specifying the serviceaccount name
- Add extra mounts
- Add environment variables

Support init containers in helm chart

---

charts/kafka-lag-exporter/templates/040-Deployment.yaml
charts/kafka-lag-exporter/values.yaml

fixes #144 Add variables to configure the liveness and readiness probes delay and timeouts in the helm chart

Configurable readiness and liveness probes in helm chart

---

build.sbt
project/Dependencies.scala
src/test/scala/com/lightbend/kafkalagexporter/integration/IntegrationSpec.scala
src/test/scala/com/lightbend/kafkalagexporter/integration/LagSim.scala
src/test/scala/com/lightbend/kafkalagexporter/integration/MetricsEvictionSpec.scala
src/test/scala/com/lightbend/kafkalagexporter/integration/SpecBase.scala

embedded-kafka is faster, but pollutes the classpath with kafka server deps when they're not needed.  embedded-kafka releases also lag Kafka, so sometimes different versions are required, which can cause conflicts on classpath as well.
Using testcontainers (Java managed Docker containers) eliminates this issue and makes it easy to test against older versions of Kafka.

Swap embedded-kafka for testcontainers

---

README.md

Since this project has been used by a number of companies and individuals in the wild I think it's fair to say it's no longer in a _beta_ state. I replaced the project status wording with a general disclaimer about it being a community project, not supported (under a commercial subscription) from Lightbend.
Fixes #141

Community and support disclaimer

---

README.md

Permissions required by Kafka Lag Exporter to run against a secured Kafka cluster

---

src/main/scala/com/lightbend/kafkalagexporter/ConsumerGroupCollector.scala
src/test/scala/com/lightbend/kafkalagexporter/integration/ExporterPorts.scala
src/test/scala/com/lightbend/kafkalagexporter/integration/IntegrationSpec.scala
src/test/scala/com/lightbend/kafkalagexporter/integration/MetricsEvictionOnFailureSpec.scala
src/test/scala/com/lightbend/kafkalagexporter/integration/MetricsEvictionSpec.scala
src/test/scala/com/lightbend/kafkalagexporter/integration/SpecBase.scala

Fixes #110
Since metric reporters can outlive collector instances, stale metrics from a failed or removed cluster (i.e. a Strimzi cluster that was deleted) will remain listed indefinitely on the prometheus endpoint.  This PR evicts all metrics that are part of the collector's offset snapshot data when the collector shuts down gracefully or due to a failure.

Evict all metrics for a cluster on collector stop or failure

---

src/main/scala/com/lightbend/kafkalagexporter/ConsumerGroupCollector.scala
src/test/scala/com/lightbend/kafkalagexporter/ConsumerGroupCollectorSpec.scala

Fix for issue #125 
By filtering NaN values before summing offsets lags, aggregate metrics for `SumGroupOffsetLagMetric` and `SumGroupTopicOffsetLagMetric`will report a more accurate value instead of NaN.

Filter Out NaN Values from Aggregate Metrics

---

charts/kafka-lag-exporter/templates/060-ServiceMonitor.yaml
charts/kafka-lag-exporter/values.yaml

Fix for : https://github.com/lightbend/kafka-lag-exporter/issues/170
Add instance label in order to distinguish between one chart and another deployed into same namespace

Support multiple instances and extra labels for service monitor

---

README.md
build.sbt
project/Dependencies.scala
src/main/scala/com/lightbend/kafkalagexporter/AppConfig.scala
src/main/scala/com/lightbend/kafkalagexporter/EndpointSink.scala
src/main/scala/com/lightbend/kafkalagexporter/GraphiteConfig.scala
src/main/scala/com/lightbend/kafkalagexporter/GraphiteEndpointConfig.scala
src/main/scala/com/lightbend/kafkalagexporter/GraphiteEndpointSink.scala
src/main/scala/com/lightbend/kafkalagexporter/InfluxDBPusherSink.scala
src/main/scala/com/lightbend/kafkalagexporter/InfluxDBPusherSinkConfig.scala
src/main/scala/com/lightbend/kafkalagexporter/MainApp.scala
src/main/scala/com/lightbend/kafkalagexporter/MetricsReporter.scala
src/main/scala/com/lightbend/kafkalagexporter/PrometheusConfig.scala
src/main/scala/com/lightbend/kafkalagexporter/PrometheusEndpointSink.scala
src/main/scala/com/lightbend/kafkalagexporter/PrometheusEndpointSinkConfig.scala
src/main/scala/com/lightbend/kafkalagexporter/SinkConfig.scala
src/test/scala/com/lightbend/kafkalagexporter/GraphiteEndpointSinkTest.scala
src/test/scala/com/lightbend/kafkalagexporter/InfluxDBPusherSinkTest.scala
src/test/scala/com/lightbend/kafkalagexporter/PrometheusEndpointSinkTest.scala

Follow up of https://github.com/lightbend/kafka-lag-exporter/pull/130 after rebasing with latest release
Note: This retains currently supported Prometheus as the default sink, if it's not configured.

Ability to extend and configure desired sink to report lag metrics, adding support to push lag metrics into InfluxDB as well

---

README.md
charts/kafka-lag-exporter/templates/030-ConfigMap.yaml
charts/kafka-lag-exporter/values.yaml
project/Dependencies.scala
src/main/scala/com/lightbend/kafkalagexporter/AppConfig.scala
src/main/scala/com/lightbend/kafkalagexporter/KafkaClient.scala
src/test/scala/com/lightbend/kafkalagexporter/KafkaClientSpec.scala

Adds the ability to blacklist Kafka consumer groups in addition to, and
supplementary to, the existing group whitelist. Resolves #69.

Add support for Consumer Group blacklisting (#69)

---

build.sbt
scripts/build_charts_index.sh
scripts/package_chart.sh
scripts/publish_charts_index.sh

Currently Helm Charts are attached to Github Release. It's enough to install chart as is.
In our case we had to extend it with our deployment specific resources. The most correct way was to make our own chart having `kafka-lag-exporter` as a dependency. But in order to specify a dependency chart must he stored in Helm Charts Repository.
In this PR I've added few steps to serve Helm Charts Repository on Github Pages as explained here https://helm.sh/docs/topics/chart_repository/.
Changes summary:
1. store chart to a separate folder instead of project root
2. Try to download existing charts index
3. Use `helm index` providing existing index to build a new repository index
4. Create github pages branch if it does not exist on github
5. Fetch  github pages branch into separate git worktree
6. …

Add release steps to serve Helm Charts Repository on Github Pages

---

examples/standalone/application.conf
examples/standalone/run-docker.sh

I started to the test `Kafka Lag Exporter` against a Confluent Cluster and failed with some strange timeout and EOF exceptions. It turned out that the docker was not up to date in the `run-docker.sh`. I updated the docker image version and also added another cluster example with sasl support (not sure if it's generally interesting xd).

Updated the standalone example with the latest docker version

---

charts/kafka-lag-exporter/templates/NOTES.txt

The URL was pointing to port 8080. But the the port-forward uses port 8000.

Fixed url in echo-statement

---

charts/kafka-lag-exporter/templates/040-Deployment.yaml

Update deployment template to use kafka_consumergroup_poll_time_ms metric for liveness and readiness probes as described in "Health Check" section of README. Using / as a healthcheck creates additional load as discussed in #49

Use kafka_consumergroup_poll_time_ms metric as healthcheck

---

charts/kafka-lag-exporter/templates/030-ConfigMap.yaml
charts/kafka-lag-exporter/values.yaml

Allow reporter properties to be configured via Helm values so
that metrics can be reported to Graphite or InfluxDB
Refs #245
Example:
```
helm template --set reporters.influxdb.enabled=true -x templates/030-ConfigMap.yaml charts/kafka-lag-exporter
...
data:
application.conf: |
kafka-lag-exporter {
port = 8000
poll-interval = 30 seconds
lookup-table-size = 60
client-group-id = "kafkalagexporter"
kafka-client-timeout = 10 seconds
clusters = [
]
reporters.prometheus.port = 8000
reporters.influxdb.endpoint = "http://influxdb"
reporters.influxdb.port = 8086
reporters.influxdb.database = "kafka_lag_exporter"
reporters.influxdb.async = true
sinks = ["PrometheusEndpointSink", "InfluxDBPusherSink"]
watchers = {
strimzi = "false"
}
metric-whitelist = [
".*"
]
}
akka {
loggers = …
```

feat: add support for different reporters in Helm chart

---

charts/kafka-lag-exporter/templates/000-ServiceAccount.yaml
charts/kafka-lag-exporter/values.yaml

As stated in the inline comment in `values.yaml`, this is useful for adding IAM roles.

support adding annotations to created service account

---

README.md

Hello,
I noticed that the readme was missing instructions to activate other reporters than Prometheus. The "sinks" configuration should indeed list all active reporters.
I have described this mechanism in the readme.

Documentation of the "sinks" config required to activate reporters

---

charts/kafka-lag-exporter/templates/040-Deployment.yaml

fixes: #339 
`imagePullSecrets` is indeed not referenced in the container spec.
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#container-v1-core

Move image pull secrets to pod spec

---

examples/k8s/strimzi-kafka-cluster.yaml

I tried to run the Minikube tests locally, and noticed from the Strimzi logs:
```
Unsupported Kafka.spec.kafka.version: 3.0.0. Supported versions are: [3.1.0, 3.1.1, 3.2.0]
```
Changing the version to `3.2.0` in `examples/k8s/strimzi-kafka-cluster.yaml` appears to make the tests run again.

Fix "Integration tests using Minikube"

---

project/Dependencies.scala
src/main/scala/com/lightbend/kafkalagexporter/watchers/StrimziClient.scala

Ref #376 376
This PR will upgrade Java dependencies and silence all warnings for Java-related vulnerabilities. `sbt test` passes locally with `docker-compose`.
Note that there are still many vulnerability warnings left, all related to the `ubi8` image.

Update dependencies to avoid known vulnerabilities

---

.github/workflows/ci.yaml
.github/workflows/release.yaml

I got errors when running the workloads on my fork, stating that "This is a scheduled Ubuntu-18.04 brownout. The Ubuntu-18.04 environment is deprecated and will be removed on December 1st, 2022." This PR upgrades Ubuntu for the workflows.

Update Ubuntu on the workflows, as 18.04 is deprecated on GitHub

---

README.md
build.sbt
charts/kafka-lag-exporter/templates/030-ConfigMap.yaml
charts/kafka-lag-exporter/values.yaml
docker/docker-compose.yml
project/Dependencies.scala
src/main/resources/reference.conf
src/main/scala/com/lightbend/kafkalagexporter/AppConfig.scala
src/main/scala/com/lightbend/kafkalagexporter/ConsumerGroupCollector.scala
src/main/scala/com/lightbend/kafkalagexporter/Domain.scala
src/main/scala/com/lightbend/kafkalagexporter/KafkaClusterManager.scala
src/main/scala/com/lightbend/kafkalagexporter/LookupTable.scala
src/main/scala/com/lightbend/kafkalagexporter/LookupTableConfig.scala
src/test/scala/com/lightbend/kafkalagexporter/ConsumerGroupCollectorSpec.scala
src/test/scala/com/lightbend/kafkalagexporter/LookupTableSpec.scala
src/test/scala/com/lightbend/kafkalagexporter/TestClock.scala
src/test/scala/com/lightbend/kafkalagexporter/TestData.scala

The lag in second metrics is really what make that exporter different from the others.
After using it for a while, I noticed the lag was really accurate when the points were inside the lookup table, but the extrapolation was really not that precise and was often leading to really high numbers.
One of the reason is when the extrapolation happens, it is done based on the entire lookup table, which works well if you have a consumer speed that don't change too much, but doesn't work well when you have a consumer that spikes.
Because of that, I tried to increase the size of the in-memory lookup table, to be able to fit between one day and one week of data but when the exporter was restarting, it took a very long time to build the lookup table.
This lead to change change, which is basically …

Adding support for Redis lookup tables

---

charts/kafka-lag-exporter/templates/030-ConfigMap.yaml

Right now, if you don't specify all the values for lookup.redis.* in the helm chart, the pod doesn't start.
An example of configuration if you specify only the host:
`
lookup-table.redis = {
host = myhost
database = 
port = 
timeout = 
prefix = 
separator = 
retention = 
expiration = 
}
`
The setting without a value should not be added, so they will inherits from the defaults in the code.

(chart) Make values in lookup.redis optional

---

charts/kafka-lag-exporter/templates/040-Deployment.yaml

The checksum/config annotation is missing in the deployment if podAnnotations is empty (that's the default value).
That make the pod not restart automatically when there is a configuration change.
The workaround is to add something in the podAnnotations, but this small code change make it simpler.

(chart) Always add checksum/config annotation

---

charts/kafka-lag-exporter/templates/030-ConfigMap.yaml
charts/kafka-lag-exporter/values.yaml
src/main/resources/reference.conf
src/main/scala/com/lightbend/kafkalagexporter/AppConfig.scala
src/main/scala/com/lightbend/kafkalagexporter/KafkaClient.scala
src/main/scala/com/lightbend/kafkalagexporter/MainApp.scala

I noticed that in some of my clusters, the exporter doesn't start.
> 2022-10-05 01:39:20,866 INFO  o.a.kafka.common.utils.AppInfoParser akka://kafka-lag-exporter/user/consumer-group-collector-kafka - Kafka version: 3.2.2
> 2022-10-05 01:39:20,866 INFO  o.a.kafka.common.utils.AppInfoParser akka://kafka-lag-exporter/user/consumer-group-collector-kafka - Kafka commitId: 38c22ad893fb6cf5
> 2022-10-05 01:39:20,866 INFO  o.a.kafka.common.utils.AppInfoParser akka://kafka-lag-exporter/user/consumer-group-collector-kafka - Kafka startTimeMs: 1664933960866
> 2022-10-05 01:39:20,867 INFO  c.l.k.ConsumerGroupCollector$ akka://kafka-lag-exporter/user/consumer-group-collector-kafka - Collecting offsets
> 2022-10-05 01:39:20,944 INFO  o.a.kafka.common.utils.AppInfoParser  - App info kafka.admin.client …

Add kafka-retries parameter

---

build.sbt

After we upgraded OpenShift, kafka-lag-exporter will no longer start:
```text
exec /opt/docker/bin/kafka-lag-exporter: permission denied
```
This is because the random-id user does not have execute permission to the executable. 
It appears from [a comment in build.sbt](https://github.com/seglo/kafka-lag-exporter/blob/master/build.sbt#L68) that the intention is to follow OpenShift best practices, but the linked document states that files and directories should be accessible to the root group, in the same way that they are accessible to the owner. This is because the random-id user that runs the container will always be part of the root group.
Instead, `build.sbt` creates a separate `kafkalagexporter` group, and assigns files and directories to that group. This PR will remove the …

Implement Openshift best practice with regard to the root group

---

charts/kafka-lag-exporter/templates/030-ConfigMap.yaml

Without the quote, the pod cannot start, as the semi column for example are not recognized as a string

Add quotes for lookup.redis.separator
