.travis.yml, src/test/scala/com/lightbend/kafkalagexporter/AppConfigSpec.scala, src/test/scala/com/lightbend/kafkalagexporter/integration/SpecBase.scala
* Test various config combinations
* Document app configuration in README.
=> Validate & document standalone config combinations

project/Dependencies.scala, src/main/scala/com/lightbend/kafkalagexporter/ConsumerGroupCollector.scala, src/main/scala/com/lightbend/kafkalagexporter/MetricsReporter.scala, src/main/scala/com/lightbend/kafkalagexporter/watchers/StrimziClusterWatcher.scala, src/test/resources/logback.xml
Upgrade dependencies.  Akka Typed is still evolving and required usage sites to be updated.
=> Upgrade dependencies

src/main/scala/com/lightbend/kafkalagexporter/ConsumerGroupCollector.scala, src/main/scala/com/lightbend/kafkalagexporter/Domain.scala, src/main/scala/com/lightbend/kafkalagexporter/KafkaClient.scala, src/test/scala/com/lightbend/kafkalagexporter/ConsumerGroupCollectorSpec.scala, src/test/scala/com/lightbend/kafkalagexporter/KafkaClientSpec.scala
=> Report NaN for group offset, lag, and time lag when no group offset returned

charts/kafka-lag-exporter/templates/030-ConfigMap.yaml
=> Allow Helm to quote Kafka client property values when necessary

charts/kafka-lag-exporter/templates/050-Service.yaml, charts/kafka-lag-exporter/templates/060-ServiceMonitor.yaml, charts/kafka-lag-exporter/values.yaml
Adds ServiceMonitor Resource in Helm Chart.
=> Add ServiceMonitor in Helm Chart Templates

build.sbt, project/Dependencies.scala, src/main/scala/com/lightbend/kafkalagexporter/KafkaClusterManager.scala, src/main/scala/com/lightbend/kafkalagexporter/MetricsSink.scala, src/main/scala/com/lightbend/kafkalagexporter/watchers/StrimziClusterWatcher.scala, src/test/resources/logback-test.xml, src/test/scala/com/lightbend/kafkalagexporter/integration/LagSim.scala, src/test/scala/com/lightbend/kafkalagexporter/integration/SpecBase.scala
Upgrade various libraries
- Akka 2.6.1
- Scala 2.12.10
- Alpakka Kafka 2.0.1
=> Upgrade deps

src/main/scala/com/lightbend/kafkalagexporter/LookupTable.scala, src/test/scala/com/lightbend/kafkalagexporter/LookupTableSpec.scala
=> Report 0 lag_ms when last reported offset == lookup offset

README.md, project/Dependencies.scala
I'll merge this and cut a release once @lilyevsky signs the CLA for #128 
Fixes #120
=> Upgrade to Apache Kafka 2.5

src/main/scala/com/lightbend/kafkalagexporter/KafkaClient.scala, src/test/scala/com/lightbend/kafkalagexporter/KafkaClientSpec.scala
=> Handle null offset in consumer group offset result

.travis.yml, README.md
+ added a docker publishLocal build step
=> Release 0.6.5

project/Dependencies.scala, src/test/resources/logback-test.xml
Increase cluster start timeouts via alpakka kafka snapshot.
=> Increase cluster timeouts

README.md
=> Document Helm chart repo as default installation method

project/plugins.sbt
=> Drop sbt-bintray

README.md
=> Add authorizer-properties to sample ACL command

README.md, charts/kafka-lag-exporter/templates/030-ConfigMap.yaml, charts/kafka-lag-exporter/templates/040-Deployment.yaml, charts/kafka-lag-exporter/values.yaml, grafana/Kafka_Lag_Exporter_Dashboard.json, project/Dependencies.scala, project/plugins.sbt
=> 0.6.8 release prep

charts/kafka-lag-exporter/templates/040-Deployment.yaml
=> Fix deployment

README.md, build.sbt
New helm repo location:
```
https://seanglover.com/kafka-lag-exporter/repo/index.yaml
```
=> Update helm repo

.travis.yml, build.sbt
References #286 based on #295 work
=> Use Java 17 inside Docker image

README.md, build.sbt
=> Refresh base image to address CVE-2022-21449

charts/kafka-lag-exporter/values.yaml
=> Set retries default to 2
